### ISSUE TITLE
点击登录报错：window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by clstudy** [caojianyu/tauri-chat#1]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/11591914/223969334-400573ce-c466-4c6a-ab63-19f45779c3f8.png">

**Comment by caojianyu** [comment]
这个不像是代码逻辑问题，检查一下看看是不是依赖的问题呢。

**Comment by clstudy** [comment]
我找到原因了，要执行` npm run tauri dev`才行，` npm run dev`会报此错误
